service: ogp-fetcher-service

provider:
  name: aws
  runtime: python3.13 # 使用するPythonのバージョン
  region: ap-northeast-1 # デプロイするAWSリージョン

functions:
  api:
    handler: wsgi_handler.handler # serverless-wsgiが生成するハンドラーを指定
    events:
      - httpApi: # API GatewayのHTTP APIを設定
          path: /api/ogp
          method: get

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: app.app # app.pyファイル内のFlaskインスタンス'app'を指定
    packRequirements: false # serverless-python-requirementsにパッケージングを任せる
  pythonRequirements:
    dockerizePip: true # 環境差異をなくすためにDockerでビルド
